const RoomTypes = {
  GET_SINGLE_ROOM_LIST: 'room/GET_SINGLE_ROOM_LIST',
  GET_SINGLE_ROOM_LIST_FAIL: 'room/GET_SINGLE_ROOM_LIST_FAIL',
  GET_SINGLE_ROOM_LIST_SUCCESS: 'room/GET_SINGLE_ROOM_LIST_SUCCESS',
  SELECT_ROOM: 'room/SELECT_ROOM',
  GET_ROOM_LIST_MESSAGE: 'room/GET_ROOM_LIST_MESSAGE',
  GET_ROOM_LIST_MESSAGE_SUCCESS: 'room/GET_ROOM_LIST_MESSAGE_SUCCESS',
  GET_ROOM_LIST_MESSAGE_FAIL: 'room/GET_ROOM_LIST_MESSAGE_FAIL',

  //message
  ADD_MESSAGE: 'room/ADD_MESSAGE',
  ADD_MESSAGE_BY_ROOMID: 'room/ADD_MESSAGE_BY_ROOMID',
  SET_ONLINE: 'room/SET_ONLINE',
  RESET_ROOM: 'room/RESET_ROOM',
};

export default RoomTypes;
