const UserTypes = {
  GET_INFO: 'user/GET_INFO',
  GET_INFO_SUCCESS: 'user/GET_INFO_SUCCESS',
  GET_INFO_FAIL: 'user/GET_INFO_FAIL',

  // modal make group
  OPEN_MODAL_MAKE_GROUP: 'user/OPEN_MODAL_MAKE_GROUP',
  CLOSE_MODAL_MAKE_GROUP: 'user/CLOSE_MODAL_MAKE_GROUP',

  OPEN_GALLERY_MODAL: 'user/OPEN_GALLERY_MODAL',
  CLOSE_GALLERY_MODAL: 'user/CLOSE_GALLERY_MODAL',
  OPEN_IMAGE_MODAL: 'user/OPEN_IMAGE_MODAL',
  CLOSE_IMAGE_MODAL: 'user/CLOSE_IMAGE_MODAL',
  OPEN_ADD_USERS_MODAL: 'user/OPEN_ADD_USERS_MODAL',
  CLOSE_ADD_USERS_MODAL: 'user/CLOSE_ADD_USERS_MODAL',
  OPEN_SETTING_MODAL: 'user/OPEN_SETTING_MODAL',
  CLOSE_SETTING_MODAL: 'user/CLOSE_SETTING_MODAL',

  SELECT_IMAGE: 'user/SELECT_IMAGE',

  RESET: 'user/RESET',
};

export default UserTypes;
