const FriendTypes = {
  GET_FRIENDS: 'friend/GET_FRIEND',
  GET_FRIENDS_FAIL: 'friend/GET_FRIEND_FAIL',
  GET_FRIENDS_SUCCESS: 'friend/GET_FRIEND_SUCCESS',
  GET_SUGGEST_LIST: 'friend/GET_SUGGEST_LIST',
  GET_SUGGEST_LIST_FAIL: 'friend/GET_SUGGEST_LIST_FAIL',
  GET_SUGGEST_LIST_SUCCESS: 'friend/GET_SUGGEST_LIST_SUCCESS',
  ADD_FRIEND: 'friend/ADD_FRIEND',
  ADD_FRIEND_FAIL: 'friend/ADD_FRIEND_FAIL',
  ADD_FRIEND_SUCCESS: 'friend/ADD_FRIEND_SUCCESS',
};

export default FriendTypes;
